In [1]:
import torch 

In [5]:
x = torch.arange(12, dtype=torch.float32)
x

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [9]:
x.numel(), 
# accessing the tensor shape
x.shape

torch.Size([12])

In [16]:
X = x.reshape(3, 4)
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [32]:
#R = x.reshape(-1, 4)
#R
S = x.reshape(3, -1)
S

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [34]:
torch.zeros(2, 3, 4)

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [35]:
torch.ones(2, 3, 4)

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [36]:
torch.randn(2, 3, 4)

tensor([[[ 0.7851,  0.3298,  2.0413,  0.2168],
         [ 0.8535,  0.4951,  1.8455, -0.4724],
         [ 0.7911, -0.6217,  0.9883, -0.9979]],

        [[ 1.4664,  0.7129, -1.4532,  1.0087],
         [-1.0745,  0.3633,  0.0293,  0.8119],
         [ 1.4946, -0.0077, -0.4349, -0.7535]]])

In [37]:
U = torch.randn(2, 3, 4)
U, U.shape

(tensor([[[-0.5560,  0.3688, -0.2615, -1.4468],
          [ 0.5043, -0.8252,  0.5919,  1.6277],
          [ 1.0489,  1.0532, -1.3801,  0.6491]],
 
         [[-1.6032, -0.6841, -2.4229, -0.1385],
          [-0.8274, -0.2425, -0.4258,  0.8252],
          [-0.2063, -0.9145,  0.3599,  1.3387]]]),
 torch.Size([2, 3, 4]))

In [49]:
X[1:3]
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [50]:
X[1, 2] = 17
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5., 17.,  7.],
        [ 8.,  9., 10., 11.]])

In [53]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x + y, x - y, x * y, x / y, x ** y

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

In [57]:
X = torch.arange(12, dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
torch.cat((X, Y), dim=0), torch.cat((X, Y), dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [59]:
X == Y 

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [60]:
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1,2))
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [61]:
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [63]:
before = id(Y)
Y  = Y + X 
id(Y) == before 

False

In [65]:
Z = torch.zeros_like(Y)
print('id(Z):', id(Z))
Z[:] = X + Y
print('id(Z):', id(Z))

id(Z): 5991021600
id(Z): 5991021600


In [1]:
import os 
import pandas as pd

os.makedirs(os.path.join('..', 'data'), exist_ok=True)
data_file = os.path.join('..', 'data', 'house_tiny.csv')
with open(data_file, 'w') as f: 
    f.write('''NumRooms, RoofType, Price
    NA, NA, 127500
    2, NA, 106000
    4, Slate, 178100
    NA, NA, 14000''')
    
data = pd.read_csv(data_file)
print(data)

  NumRooms  RoofType   Price
0       NA        NA  127500
1        2        NA  106000
2        4     Slate  178100
3       NA        NA   14000


In [3]:
pip install ucimlrepo

Note: you may need to restart the kernel to use updated packages.


In [ ]:
from ucimlrepo import fetch_ucirepo 
  
# fetch dataset 
abalone = fetch_ucirepo(id=1) 
  
# data (as pandas dataframes) 
X = abalone.data.features 
y = abalone.data.targets 
  
# metadata 
print(abalone.metadata) 
  
# variable information 
print(abalone.variables) 


In [1]:
import torch 

In [2]:
x = torch.tensor(3.0)
y = torch.tensor(2.0)

x + y, x * y, x / y, x ** y

(tensor(5.), tensor(6.), tensor(1.5000), tensor(9.))

In [5]:
x = torch.arange(3)
x, x[2], x.numel() == len(x)

(tensor([0, 1, 2]), tensor(2), True)

In [7]:
A = torch.arange(6).reshape(3, 2) 
A, A.T 

(tensor([[0, 1],
         [2, 3],
         [4, 5]]),
 tensor([[0, 2, 4],
         [1, 3, 5]]))

In [9]:
torch.arange(24).reshape(2, 3, 4)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [10]:
A = torch.arange(6, dtype=torch.float32).reshape(2, 3)
B = A.clone() #Assign a copy of A to B by allocationg new memory 
A, A + B

(tensor([[0., 1., 2.],
         [3., 4., 5.]]),
 tensor([[ 0.,  2.,  4.],
         [ 6.,  8., 10.]]))

In [13]:
A * B 

tensor([[ 0.,  1.,  4.],
        [ 9., 16., 25.]])

In [14]:
a = 2
X = torch.arange(24).reshape(2, 3, 4)
a + X, (a * X).shape

(tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]),
 torch.Size([2, 3, 4]))

In [15]:
x = torch.arange(3, dtype=torch.float32)
x, x.sum()

(tensor([0., 1., 2.]), tensor(3.))

In [16]:
A.shape, A.sum()

(torch.Size([2, 3]), tensor(15.))

In [17]:
A

tensor([[0., 1., 2.],
        [3., 4., 5.]])

In [18]:
A.shape, A.sum(axis=0).shape

(torch.Size([2, 3]), torch.Size([3]))

In [20]:
A.mean(), A.sum()/A.numel()

(tensor(2.5000), tensor(2.5000))

In [21]:
sum_A = A.sum(axis=1, keepdims=True)
sum_A, sum_A.shape

(tensor([[ 3.],
         [12.]]),
 torch.Size([2, 1]))

In [26]:
y = torch.ones(3, dtype=torch.float32)
x, y, torch.dot(x, y), torch.dot(x, y) == torch.sum(x * y)

(tensor([0., 1., 2.]), tensor([1., 1., 1.]), tensor(3.), tensor(True))

In [27]:
A.shape, x.shape, torch.mv(A, x), A@x

(torch.Size([2, 3]), torch.Size([3]), tensor([ 5., 14.]), tensor([ 5., 14.]))

In [28]:
A, x

(tensor([[0., 1., 2.],
         [3., 4., 5.]]),
 tensor([0., 1., 2.]))

In [30]:
B = torch.ones(3, 4)
torch.mm(A, B), A@B

(tensor([[ 3.,  3.,  3.,  3.],
         [12., 12., 12., 12.]]),
 tensor([[ 3.,  3.,  3.,  3.],
         [12., 12., 12., 12.]]))

In [31]:
u = torch.tensor([3.0, -4.0])
torch.norm(u)

tensor(5.)

In [34]:
x = torch.arange(4.0, requires_grad=True)
x, x.grad

(tensor([0., 1., 2., 3.], requires_grad=True), None)

In [35]:
y = 2 * torch.dot(x, x)
y 

tensor(28., grad_fn=<MulBackward0>)

In [36]:
y.backward()
x.grad

tensor([ 0.,  4.,  8., 12.])

In [37]:
x.grad == 4 * x

tensor([True, True, True, True])

In [38]:
x

tensor([0., 1., 2., 3.], requires_grad=True)

In [39]:
%matplotlib inline
import math 
import time 
import numpy as np 
from d2l import torch as d2l 