In [1]:
import torch

In [2]:
x = torch.tensor(3.0)
y = torch.tensor(2.0)
x + y, x * y, x/y, x**y

(tensor(5.), tensor(6.), tensor(1.5000), tensor(9.))

In [4]:
z = torch.arange(3)
z

tensor([0, 1, 2])

In [9]:
len(z)

3

In [10]:
z.shape

torch.Size([3])

Matrices are 2nd order tensors. They are tensors with two axes.

In [15]:
A = torch.arange(6).reshape(3, 2)
A

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [17]:
help(torch.reshape)

Help on built-in function reshape in module torch:

reshape(...)
    reshape(input, shape) -> Tensor
    
    Returns a tensor with the same data and number of elements as :attr:`input`,
    but with the specified shape. When possible, the returned tensor will be a view
    of :attr:`input`. Otherwise, it will be a copy. Contiguous inputs and inputs
    with compatible strides can be reshaped without copying, but you should not
    depend on the copying vs. viewing behavior.
    
    See :meth:`torch.Tensor.view` on when it is possible to return a view.
    
    A single dimension may be -1, in which case it's inferred from the remaining
    dimensions and the number of elements in :attr:`input`.
    
    Args:
        input (Tensor): the tensor to be reshaped
        shape (tuple of int): the new shape
    
    Example::
    
        >>> a = torch.arange(4.)
        >>> torch.reshape(a, (2, 2))
        tensor([[ 0.,  1.],
                [ 2.,  3.]])
        >>> b = torch.tensor([[0, 

In [19]:
B = torch.arange(10)
B

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
C = torch.reshape(B, (5, 2))
C

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [23]:
A, C

(tensor([[0, 1],
         [2, 3],
         [4, 5]]),
 tensor([[0, 1],
         [2, 3],
         [4, 5],
         [6, 7],
         [8, 9]]))

In [24]:
A.T

tensor([[0, 2, 4],
        [1, 3, 5]])

In [25]:
C.T

tensor([[0, 2, 4, 6, 8],
        [1, 3, 5, 7, 9]])

In [31]:
C[2,1]

tensor(5)

The elementwise product of two matrices is called theri Hadamard product. Below, we spell out the entires of the Hadamard product of two matrices. By the way, it is important that they have the same shape.

In [32]:
A, B

(tensor([[0, 1],
         [2, 3],
         [4, 5]]),
 tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]))

In [33]:
A.shape

torch.Size([3, 2])

In [34]:
D = torch.arange(6).reshape(3, 2)

In [35]:
D.shape

torch.Size([3, 2])

In [36]:
D.shape == A.shape

True

In [37]:
A * D

tensor([[ 0,  1],
        [ 4,  9],
        [16, 25]])

The operation above performs the element wise multiplication of the matrices A, and D. 

In [38]:
A

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [39]:
D

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [41]:
A + D

tensor([[ 0,  2],
        [ 4,  6],
        [ 8, 10]])

In [43]:
x

tensor(3.)

In [44]:
A

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [47]:
x * A

tensor([[ 0.,  3.],
        [ 6.,  9.],
        [12., 15.]])

Multiplication of a matrix by a scalar. It produces a matrix or a 2th order tensor with the same shape as the orinal one.

## 2.3.6. Reduction

Often, we wish to calculate the sum of a tensor's elements. To express the sum of the elements in a vector, there is a simple function for it:

In [48]:
z

tensor([0, 1, 2])

In [49]:
z.sum()

tensor(3)

for higher oder tensor the rule maintains, here it goes:

In [50]:
A.sum()

tensor(15)

In [51]:
A

tensor([[0, 1],
        [2, 3],
        [4, 5]])

A related quantity is the mean, also called the average. We calculate the mean by dividing the sum by the toal number of elements. Because computing the mean is so common, it gets a dedicated library functions tht works analogously to sum. 

In [56]:
E = x * A
E

tensor([[ 0.,  3.],
        [ 6.,  9.],
        [12., 15.]])

In [58]:
print("This is the average: summing all the elements in the tensosr")
E.mean()

This is the average: summing all the elements in the tensosr


tensor(7.5000)

Number of elements in the tensor:

In [59]:
E.numel()

6

## 2.3.8. Dot Products

We can calculate the dot product of two vectors by performing an elementwise multiplication followed by a sum. 

In [60]:
help(torch.dot)

Help on built-in function dot in module torch:

dot(...)
    dot(input, other, *, out=None) -> Tensor
    
    Computes the dot product of two 1D tensors.
    
    .. note::
    
        Unlike NumPy's dot, torch.dot intentionally only supports computing the dot product
        of two 1D tensors with the same number of elements.
    
    Args:
        input (Tensor): first tensor in the dot product, must be 1D.
        other (Tensor): second tensor in the dot product, must be 1D.
    
    Keyword args:
        out (Tensor, optional): the output tensor.
    
    Example::
    
        >>> torch.dot(torch.tensor([2, 3]), torch.tensor([2, 1]))
        tensor(7)



# NOTE:

Dot product is a scalar value, it is also called scalar product. Do not confuse it with matrix multiplication. Dot product is perfomed with 1th order tensors or 1D tensor!!

In [61]:
z

tensor([0, 1, 2])

In [62]:
t = torch.arange(3)
t

tensor([0, 1, 2])

In [63]:
torch.dot(z,t)

tensor(5)

## 2.3.9. Matrix-Vector Products

Matrix-vector products also describe the key calculation involved in computing the outputs of each layer in a neural network given the outputs from the previous layer.

To express a matrix-vector product in code, we use the mv function. Note that the column dimension of A (its length along axis 1) must be the same as the dimension of x (its length).

PyTorch has a convenience operator @ that can execute both matrix-vector and matrix-matrix products (depending on its arguments). Thus we can write A@x.

In [70]:
z.reshape(1,3)

tensor([[0, 1, 2]])

In [73]:
A.shape

torch.Size([3, 2])

In [76]:
z.shape

torch.Size([3])

In [80]:
print("reshaping tensor A")
F = A.reshape(2, 3)

reshaping tensor A


In [81]:
F

tensor([[0, 1, 2],
        [3, 4, 5]])

In [82]:
z

tensor([0, 1, 2])

Now checking that the shapes match:

In [83]:
torch.mv(F, z)

tensor([ 5, 14])

and now using the @ operator

In [84]:
F@z

tensor([ 5, 14])

testing both results

In [85]:
torch.mv(F, z) == F@z

tensor([True, True])

In [86]:
help(torch.mv)

Help on built-in function mv in module torch:

mv(...)
    mv(input, vec, *, out=None) -> Tensor
    
    Performs a matrix-vector product of the matrix :attr:`input` and the vector
    :attr:`vec`.
    
    If :attr:`input` is a :math:`(n \times m)` tensor, :attr:`vec` is a 1-D tensor of
    size :math:`m`, :attr:`out` will be 1-D of size :math:`n`.
    
    .. note:: This function does not :ref:`broadcast <broadcasting-semantics>`.
    
    Args:
        input (Tensor): matrix to be multiplied
        vec (Tensor): vector to be multiplied
    
    Keyword args:
        out (Tensor, optional): the output tensor.
    
    Example::
    
        >>> mat = torch.randn(2, 3)
        >>> vec = torch.randn(3)
        >>> torch.mv(mat, vec)
        tensor([ 1.0404, -0.6361])



## 2.3.10. Matrix-Matrix Multiplication

Matrix-Matrix multiplication is basically the dot product of the ith column in matrix B to the ith row in matrix A.

In [89]:
F.shape

torch.Size([2, 3])

In [91]:
G = torch.ones(3, 4)
G

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [94]:
print("Now the matrix-matrix multiplication using two different methods")


Now the matrix-matrix multiplication using two different methods


In [95]:
A = torch.arange(6, dtype=torch.float32).reshape(2, 3)
A

tensor([[0., 1., 2.],
        [3., 4., 5.]])

In [96]:
torch.mm(A, G)

tensor([[ 3.,  3.,  3.,  3.],
        [12., 12., 12., 12.]])

In [97]:
A@G

tensor([[ 3.,  3.,  3.,  3.],
        [12., 12., 12., 12.]])

In [99]:
torch.mm(A, G) == A@G


tensor([[True, True, True, True],
        [True, True, True, True]])

Interesting note tho, is that the official documentation says that this function torch.mm does not broadcast. And if the result is supposed to be broadcasted then one should use torch.matmul() instead. 

## 2.3.11. Norms

A norm is a function that maps a vector to a scalar.

In [100]:
u = torch.tensor([3.0, -4.0])
torch.norm(u)

tensor(5.)

Note: torch.norm is deprecated and may be removed in a future PyTorch release. Use torch.linalg.norm(), instead, or torch.linalg.vector_norm() when computring vector norms and torch.linalg.matrix_norm() when computing matrix norms. 

In [101]:
torch.norm(torch.ones(4, 9))

tensor(6.)

# 22.1. Geometry and Linear Algebraic Operations

Vectors usually have different interpretations, where data examples are column vectors and weights used to form weighted sums are row vectors. However, it can be beneficial to be flexible. Although a single vector's default orientation is a column vector, for any matrix representing a tabular dataset, treating each data example as a row vector in the matrix is more conventional. 