# PyTorch Fundamentals: 

* Introduction to Tensors
* Creating Tensors
* Getting information from tensors
* Manipulating Tensors
* Dealing with tensor shapes
* Indexing on tensors
* Mixing Pytorch tensors and Numpy
* Reproducibility
* Running Tensors on GPU

In [1]:
import torch
torch.__version__

'1.13.1'

## Creating Tensors

In [2]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
# we can check the dimensions of a tensor using the ndim attribute
scalar.ndim 

0

In [4]:
# retrieve the number from the tensor?
scalar.item()  # only works with one-element tensor

7

In [6]:
# vector 
vector = torch.tensor([7, 7])
# check the number of dimension of a vector 
vector.ndim, vector

(1, tensor([7, 7]))

### Tip: 
You can tell the number of dimensions a tensor in PyTorch has by the number of square brackets on the outside, and you only need to count one side. 

In [7]:
# Matrix 

matrix = torch.tensor([[7, 8], 
                      [9, 10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [8]:
# numbe of dimensions and shape 
matrix.ndim, matrix.shape

(2, torch.Size([2, 2]))

In [9]:
# Tensor

TENSOR = torch.tensor([[[1, 2, 3], 
                       [3, 6, 9], 
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [10]:
TENSOR.ndim, TENSOR.shape

(3, torch.Size([1, 3, 3]))

That means there's 1 dimension of 3 by 3. 

In [11]:
# random tenosr of size (3, 4)
random_tensor = torch.rand(size=(3, 4))
random_tensor, random_tensor.dtype

(tensor([[0.5244, 0.6145, 0.7545, 0.8273],
         [0.4510, 0.8889, 0.0257, 0.3589],
         [0.8162, 0.9642, 0.0048, 0.9739]]),
 torch.float32)

In [14]:
# tensor all zeros or ones

zeros = torch.zeros(size=(3, 4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [15]:
ones = torch.ones(size=(3, 4))
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

In [16]:
# use torch.arange, torch.range() is deprecated
zero_to_ten = torch.arange(start=0, end=10, step=1)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

__Sometimes you might want one tensor of a certain type with the same shape as another tensor.__ For example, a tensor of all zeros with the same shape as a previous tensor. 

You can use the following function torch.zeros_like(input) or torch.ones_like(input) which return a tensor filled with zeros or ones in the same shape as the input respectively. 

In [17]:
# can also create a tensor of zeros similar to another tensor
ten_zeros = torch.zeros_like(input=zero_to_ten) 
# will have the same shape
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes
[tensor datatypes available in PyTorch](https://pytorch.org/docs/stable/tensors.html#data-types)

In [18]:
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations performed on the tensor are recorded 

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [19]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16) # torch.half would also work

float_16_tensor.dtype

torch.float16

## Getting information from tensors

In [20]:
# Create a tensor
some_tensor = torch.rand(3, 4)

# Find out details about it
print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}") # will default to CPU

tensor([[0.2328, 0.5234, 0.6285, 0.8774],
        [0.9962, 0.4688, 0.7606, 0.7026],
        [0.2522, 0.0775, 0.3592, 0.6142]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


## Manipulating tensors (tensor operations)

### Basic Operations: 

In [21]:
# Create a tensor of values and add a number to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [22]:
# Multiply it by 10
tensor * 10

tensor([10, 20, 30])


Notice how the tensor values above didn't end up being tensor([110, 120, 130]), this is because the values inside the tensor don't change unless they're reassigned.

In [23]:
# Tensors don't change unless reassigned
tensor

tensor([1, 2, 3])

In [24]:
# Subtract and reassign
tensor = tensor - 10
tensor

tensor([-9, -8, -7])

In [25]:
# Add and reassign
tensor = tensor + 10
tensor

tensor([1, 2, 3])

In [26]:
# Can also use torch functions
torch.multiply(tensor, 10)

tensor([10, 20, 30])

In [27]:
# Original tensor is still unchanged 
tensor

tensor([1, 2, 3])

In [28]:
# Element-wise multiplication (each element multiplies its equivalent, index 0->0, 1->1, 2->2)
print(tensor, "*", tensor)
print("Equals:", tensor * tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


## Reproducibility

In [29]:
# Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(f"Tensor A:\n{random_tensor_A}\n")
print(f"Tensor B:\n{random_tensor_B}\n")
print(f"Does Tensor A equal Tensor B? (anywhere)")
random_tensor_A == random_tensor_B

Tensor A:
tensor([[0.7105, 0.9557, 0.6316, 0.7119],
        [0.1324, 0.5047, 0.2468, 0.1721],
        [0.5781, 0.0048, 0.7221, 0.8578]])

Tensor B:
tensor([[0.2022, 0.1959, 0.0904, 0.0893],
        [0.6327, 0.7845, 0.5804, 0.5194],
        [0.0716, 0.9811, 0.2953, 0.9957]])

Does Tensor A equal Tensor B? (anywhere)


tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

Just as you might've expected, the tensors come out with different values.

But what if you wanted to created two random tensors with the same values.

As in, the tensors would still contain random values but they would be of the same flavour.

That's where torch.manual_seed(seed) comes in, where seed is an integer (like 42 but it could be anything) that flavours the randomness.

Let's try it out by creating some more flavoured random tensors.

In [33]:
import random

# # Set the random seed
RANDOM_SEED=42 # try changing this to different values and see what happens to the numbers below
torch.manual_seed(seed=RANDOM_SEED) 
random_tensor_C = torch.rand(3, 4)

# Have to reset the seed every time a new rand() is called 
# Without this, tensor_D would be different to tensor_C 
torch.random.manual_seed(seed=RANDOM_SEED) # try commenting this line out and seeing what happens
random_tensor_D = torch.rand(3, 4)

print(f"Tensor C:\n{random_tensor_C}\n")
print(f"Tensor D:\n{random_tensor_D}\n")
print(f"Does Tensor C equal Tensor D? (anywhere)")
random_tensor_C == random_tensor_D

Tensor C:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Tensor D:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Does Tensor C equal Tensor D? (anywhere)


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

* [The PyTorch reproducibility documentation](https://pytorch.org/docs/stable/notes/randomness.html)
* [The Wikipedia random seed page](https://en.wikipedia.org/wiki/Random_seed)