In [1]:
import torch

In [3]:
a = torch.arange(3).reshape(3, 1)
b = torch.arange(2).reshape(1, 2)
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

Since a and b are 3 x 1 and 1 x 2 mattrices, respectively, theri shapes do not match up. Broadcasting produces a larger 3 x 2 matrix by replicating matrix a along the colums and matrix b along the rows before adding them elementwise.

In [4]:
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

## What is Broadcasting?

In the context of deep learning, we sometimes use less conventional notation. We allows the addition of a matrix and a vector: C = A + b where Cij = Aij + b. In other words the vector b is added to each row of the matrix. 

In [7]:
C = torch.arange(6).reshape(3, 2)
C

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [8]:
b 

tensor([[0, 1]])

In [9]:
C + b

tensor([[0, 2],
        [2, 4],
        [4, 6]])

Creating another vector jus to clearly see this idea of the vector being added to each row of the matrix. Not forgetting that the resulting vector actually maintains the original matrix size or shape.

In [10]:
d = torch.arange(1, 3)

In [11]:
C

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [12]:
d

tensor([1, 2])

Now additing them to check the broadcasting mechanism:

In [13]:
C + d

tensor([[1, 3],
        [3, 5],
        [5, 7]])